name: Build STM32 Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Generate Binary
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install ARM GCC Toolchain
      run: |
        # Install dependencies
        sudo apt-get update
        sudo apt-get install -y wget unzip
        
        # Download ARM GCC toolchain
        wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-linux-x86_64.tar.gz
        
        # Extract and install
        tar -xzf gcc-arm-none-eabi-10.3-2021.10-linux-x86_64.tar.gz
        sudo mv gcc-arm-none-eabi-10.3-2021.10 /usr/local/gcc-arm
        sudo ln -s /usr/local/gcc-arm/bin/arm-none-eabi-* /usr/local/bin/

    - name: Build the project
      run: |
        cd ${{ github.workspace }}/project_desd
        make clean all  # Adjust if needed based on your Makefile or build system

    - name: Generate binary file
      run: |
        arm-none-eabi-objcopy -O binary ${{ github.workspace }}/project_desd/Debug/project_desd.elf ${{ github.workspace }}/project_desd/Debug/project_desd.bin

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v3
      with:
        name: STM32-Binary
        path: ${{ github.workspace }}/project_desd/Debug/project_desd.bin
