name: Build STM32 Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Generate Binary
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up ARM GCC Toolchain
      uses: Arm-Development/ACTION-setup-arm-toolchain@v1
      with:
        version: '10.3-2021.10'  # Specify the ARM GCC toolchain version

    - name: Set up STM32CubeIDE
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5 libncursesw5 zlib1g libssl-dev
        # Additional dependencies for STM32CubeIDE if required

    - name: Build the project
      run: |
        cd ${{ github.workspace }}/project_desd
        make clean all  # Adjust if needed based on your Makefile or build system

    - name: Generate binary file
      run: |
        arm-none-eabi-objcopy -O binary ${{ github.workspace }}/project_desd/Debug/project_desd.elf ${{ github.workspace }}/project_desd/Debug/project_desd.bin

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v3
      with:
        name: STM32-Binary
        path: ${{ github.workspace }}/project_desd/Debug/project_desd.bin
