name: Build STM32 Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Generate Binary
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install ARM GCC Toolchain
      run: |
        # Install dependencies
        sudo apt-get update
        sudo apt-get install -y wget bzip2
        
        # Download ARM GCC toolchain
        wget "https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2?rev=78196d3461ba4c9089a67b5f33edf82a&hash=5631ACEF1F8F237389F14B41566964EC" -O gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2
        
        # Extract and install
        tar -xjf gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2
        sudo mv gcc-arm-none-eabi-10.3-2021.10 /usr/local/gcc-arm
        sudo ln -s /usr/local/gcc-arm/bin/arm-none-eabi-* /usr/local/bin/

    - name: Build the project
      run: |
        cd ${{ github.workspace }}/project_desd/Debug/
        make clean all  # Adjust if needed based on your Makefile or build system

    - name: Generate binary file
      run: |
        arm-none-eabi-objcopy -O binary ${{ github.workspace }}/project_desd/Debug/project_desd.elf ${{ github.workspace }}/project_desd/Debug/project_desd.bin

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v3
      with:
        name: STM32-Binary
        path: ${{ github.workspace }}/project_desd/Debug/project_desd.bin
